version: "3"

services:
  mongodb:
    image: mongo
    ports:
    - 27018:27017
    restart: always

  stream-registry:
    environment:
      ALLOWED_ORIGIN: "*"
      DB_HOSTNAME: mongodb
      CLEANER_DELAY: 60000
      PROFILE: prod
    image: anatoliy57/stream-registry:latest
    ports: 
    - 8080:8080
    links:
    - mongodb
    depends_on:
    - mongodb

  adapter:
    image: anatoliy57/amazon-cognito-adapter:latest
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILE=prod
      - LOG_LEVEL=debug

  api-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7070:7070
    environment:
      - AmazonCognitoAdapter="adapter:9090"
      - StreamRegistry="stream-registry:8080"
